/* Generated by: ParserGeneratorCC: Do not edit this line. ParserConstants.java */
package ru.vsu.cs.course4.lang;


/**
 * Token literal values and constants.
 * Generated by com.helger.pgcc.output.java.OtherFilesGenJava#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WS = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 2;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 3;
  /** RegularExpression Id. */
  int LETTER = 4;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int INT_VALUE = 6;
  /** RegularExpression Id. */
  int FLOAT_VALUE = 7;
  /** RegularExpression Id. */
  int ESCAPE = 8;
  /** RegularExpression Id. */
  int CHAR_VALUE = 9;
  /** RegularExpression Id. */
  int STRING_VALUE = 10;
  /** RegularExpression Id. */
  int ACCESS_MODIFIER = 11;
  /** RegularExpression Id. */
  int BRANCH = 12;
  /** RegularExpression Id. */
  int IF = 13;
  /** RegularExpression Id. */
  int ELSE = 14;
  /** RegularExpression Id. */
  int FOR = 15;
  /** RegularExpression Id. */
  int WHILE = 16;
  /** RegularExpression Id. */
  int DO = 17;
  /** RegularExpression Id. */
  int FUNCTION = 18;
  /** RegularExpression Id. */
  int RETURN = 19;
  /** RegularExpression Id. */
  int IDENT = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WS>",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<LETTER>",
    "<DIGIT>",
    "<INT_VALUE>",
    "<FLOAT_VALUE>",
    "<ESCAPE>",
    "<CHAR_VALUE>",
    "<STRING_VALUE>",
    "<ACCESS_MODIFIER>",
    "\"branching\"",
    "\"if\"",
    "\"else\"",
    "\"for\"",
    "\"while\"",
    "\"do\"",
    "\"function\"",
    "\"return\"",
    "<IDENT>",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"+\"",
    "\"-\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\";\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
  };

}
